### ISSUE TITLE
Convert Bartender to be a Yeoman workflow and split each task/config into it's own repo

### ISSUE THREAD

**Issue by geebru** [LookThink/bartender#1]
To keep Bartender as modular, yet easy to use, as possible we've decided to split tasks and configurations into their own repos for easier management.

Bartender will become a Yeoman workflow that sets up a project, pulls whichever tasks the project needs, and installs relevant dependencies.

**Tasks**:
- [ ] Break out each task into a separate repo with a config.yml and task.js
- [ ] Allow Bartender users to use Yeoman to build the project

**Yeoman should allow the following options:**
- [ ] Project Name
- [ ] Primary Developer Name
- [ ] Source Folder
- [ ] Destination Folder
- [ ] Tasks required (Yes/No or A/B selections)
- [ ] Browser Support (Option for which legacy IE version to use)
- [ ] ES5 vs ES6

**Output should include:**
- [ ] User defined source and destination folders with relevant subfolders
- [ ] Gulp folder, gulpfile.js, and package.json with relevant requirements and files
- [ ] Tasks file with individual task.js files chosen during install
- [ ] Concatenated config.yml file with configurations for each chosen module
- [ ] README consisting of the information chosen
